#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Iulia-Rebeca Lupaș
url: 'https://iuliarebecalupas.github.io'

description: Personal resume and IT learning journey

theme_skin: turquoise # blue turquoise green berry orange ceramic teal oceanstale

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
